# Generated by Django 5.2.6 on 2025-10-18 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portafolio',
            fields=[
                ('id_portafolio', models.IntegerField(primary_key=True, serialize=False)),
                ('id_usuario', models.IntegerField()),
                ('nombre', models.CharField(max_length=255)),
                ('fecha', models.DateTimeField()),
                ('descripcion', models.TextField()),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'verbose_name': 'Portafolio',
                'verbose_name_plural': 'Portafolios',
                'db_table': 'Portafolio',
            },
        ),
    ]
